### ISSUE TITLE
possible security leaks

### ISSUE THREAD

**Issue by valeriocos** [hrshadhin/hrsweb#1]
Hello,

I'm part of a research team and we have developed a tool (available at https://github.com/atlanmod/web-application-security/tree/master/web.security.checker) to automatically test security properties for Java EE applications.

We have identified that some methods are left unprotedted in your configuration. We would like to confirm if this is the intended behaviour or an anomaly of the configuration

We can send you the complete security report if you are interested in.

cheers

**Comment by hrshadhin** [comment]
Yes i'm interested. Please send me th complete security report.

**Comment by valeriocos** [comment]
ok, I'm going to send you the security report by email

**Comment by hrshadhin** [comment]
i didn't find any security fault issue in your reports.

------------------------------
হাবিবুর রহমান স্বাধীন
মুঠোফোন:+৮৮০১৫৫৪৩২২৭০৭
সেচ্ছাসেবক,এফওএসএস বাংলাদেশ
সহকারী বিশ্লেষক,লুমেক্সটেক সফ্টওয়্যার সলিউশনস  লিমিটেড

2015-05-11 13:45 GMT+06:00 valerio <notifications@github.com>:

**Comment by valeriocos** [comment]
sorry, I made a mistake. it wasn't the right repository. I should have contacted this one: https://github.com/pavan-dh/hrs/tree/master/hrs-web
